name: ci-pr

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - uses: mydea/actions-ember-testing@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test:ember
      - name: Lint
        run: |
          yarn lint:js
          yarn lint:hbs

  test-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        # Keep this in sync with config/ember-try.js
        ember:
          [
            ember-lts-4.12,
            ember-lts-5.4,
            ember-lts-5.8,
            ember-release,
          ]

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - uses: mydea/actions-ember-testing@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test:one ${{ matrix.ember }}
